### ISSUE TITLE
Undefined offset:     1

### ISSUE THREAD

**Issue by timmillwood** [relaxedws/drupal-relaxed#35]
The following lines in src/HttpMultipart/Message/MultipartResponse.php are causing "Undefined offset: 1" notices.

Line: 60

```
list($header_lines, $body) = explode("\r\n\r\n", $message, 2);
```

Line: 62

```
list($key, $value) = preg_split('/:\s+/', $header_line, 2);
```

**Comment by dickolsson** [comment]
Closing this in favor of the d.o issue that I opened instead: https://www.drupal.org/node/2600434
