### ISSUE TITLE
unable to move content from dev to stage

### ISSUE THREAD

**Issue by manojkukkala** [relaxedws/drupal-relaxed#95]
#Hi tim,
I followed same steps you did. 
I am trying to push from dev to stage. After I push then nothing is happening. I am not getting deployment sucessfull. Can u help me to fix this issue?

when I go to status report I see below information

The relaxedws/replicator library is not available

**Comment by jeqq** [comment]
See my comment here: https://www.drupal.org/project/relaxed/issues/2925101#comment-12352222
